bazel:
  default: 0.22.0
  versions: [
    0.22.0,
    0.21.0,
    0.20.0,
    0.19.2,
    0.19.1,
    0.19.0,
    0.18.1,
    0.18.0,
    0.17.2,
    0.17.1,
  ]

compilers:
- name: gcc
  default: 8
  versions: [
    8, 8.2, 8.2.0,
    7, 7.3, 7.3.0,
    6, 6.4, 6.4.0,
    5, 5.5, 5.5.0,
    4, 4.9, 4.9.4,
  ]
